name: Eightful
options:
  bundleIdPrefix: org.whitelabel
  deploymentTarget:
    iOS: "16.0"
    watchOS: "9.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  developmentLanguage: en

packages:
  EightfulCore:
    path: .

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    WATCHOS_DEPLOYMENT_TARGET: "9.0"
    GENERATE_INFOPLIST_FILE: NO
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 86H54WCPYP

targets:

  Eightful:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App/iOS
        excludes:
          - "Info.plist"
          - "*.entitlements"
      - path: App/Shared
    dependencies:
      - package: EightfulCore
        product: EightfulCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.whitelabel.eightful
        INFOPLIST_FILE: App/iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/iOS/Eightful.entitlements
        TARGETED_DEVICE_FAMILY: "1"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"

  EightfulWatch:
    type: application
    platform: watchOS
    deploymentTarget: "9.0"
    sources:
      - path: App/Watch
        excludes:
          - "Info.plist"
          - "*.entitlements"
      - path: App/Shared
    dependencies:
      - target: EightfulComplication
        embed: true
      - package: EightfulCore
        product: EightfulCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.whitelabel.eightful.watchkitapp
        INFOPLIST_FILE: App/Watch/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Watch/EightfulWatch.entitlements
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"

  EightfulComplication:
    type: app-extension
    platform: watchOS
    deploymentTarget: "9.0"
    sources:
      - path: App/Complication
        excludes:
          - "Info.plist"
          - "*.entitlements"
      - path: App/Shared
    dependencies:
      - package: EightfulCore
        product: EightfulCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.whitelabel.eightful.watchkitapp.widget
        INFOPLIST_FILE: App/Complication/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Complication/EightfulComplication.entitlements
        SKIP_INSTALL: YES
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"

schemes:
  Eightful:
    build:
      targets:
        Eightful: all
    run:
      config: Debug
    archive:
      config: Release

  EightfulWatch:
    build:
      targets:
        EightfulWatch: all
    run:
      config: Debug
    archive:
      config: Release
